CREATE TABLE trigger_queue (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    event_payload TEXT NOT NULL, -- JSON representation of BranchUpdateEvent
    status TEXT NOT NULL DEFAULT 'PENDING', -- PENDING, PROCESSING, COMPLETED, FAILED
    retry_count INTEGER NOT NULL DEFAULT 0,
    next_retry_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
