CREATE TABLE trigger_queue (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    event_payload TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDING',
    retry_count INTEGER NOT NULL DEFAULT 0,
    next_retry_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status_updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
