ALTER TABLE trigger_queue ADD COLUMN status TEXT NOT NULL DEFAULT 'PENDING';
ALTER TABLE trigger_queue ADD COLUMN next_retry_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE trigger_queue ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
