name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_TEST_DEBUG: 0
  CARGO_PROFILE_DEV_DEBUG: 0

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Typos
        uses: crate-ci/typos@v1

      - name: Toolchain Setup
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Formatting
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --locked --all-targets --all-features -- -D warnings

      - name: Documentation
        run: cargo doc --locked --all-features --no-deps --document-private-items

  test_and_build:
    name: Test and Build
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Toolchain Setup
        uses: dtolnay/rust-toolchain@stable

      - name: Install Nextest
        uses: taiki-e/install-action@nextest

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Tests
        run: cargo nextest run --locked --all-features --no-tests=pass

      - name: Build
        run: cargo build --locked --release
